### ISSUE TITLE
update NGA

### ISSUE THREAD

**Issue by RoyStegeman** [N3PDF/evolutionary_keras#20]
Should we just return an error if the network does not have only weight-bias structures? As in that case the NGA functionality is not well suited.

**Comment by scarlehoff** [comment]
This would be a nice feature to have but it needs to take into account the issue discussed in #21 as we cannot rely on the input layer being just `Dense`.

**Comment by RoyStegeman** [comment]
In that case I think the only way to do this is to check whether the shapes of the trainable parameters are such that they could correspond to such a structure. 

But is it really worth adding these kind of features if there are no plans to use them?

**Comment by scarlehoff** [comment]
Well, it is an enhancement that would be nice. Wouldn't say it's a required feature by any means, no.

Mainly because it would be not trivial to do a check general enough that can capture any possible situation...
