### ISSUE TITLE
Weight undo_flatten method bug

### ISSUE THREAD

**Issue by europaer** [N3PDF/evolutionary_keras#34]
There is a bug in the undo_flatten method inside the CMA optimizer. The weights are not well positioned back in place because length_flat_layer contains lengths and not indices.

```
for i, layer_shape in enumerate(self.shape):
    flat_layer = flattened_weights[
                           self.length_flat_layer[i]: self.length_flat_layer[i] + self.length_flat_layer[i + 1]
                      ]
```
This could be a quick fix
```
index_start = self.length_flat_layer[i] + sum(self.length_flat_layer[:i])
index_end = index_start + self.length_flat_layer[i + 1]
flat_layer = weights_flattened[index_start:index_end]
```

**Comment by RoyStegeman** [comment]
Ah yes, you are absolutely correct, the starting index should have been calculated cumulatively. Thanks for pointing this out!
