### ISSUE TITLE
PyPI & Anaconda package

### ISSUE THREAD

**Issue by scarlehoff** [N3PDF/evolutionary_keras#7]

**Comment by scarlehoff** [comment]
@scarrazza do we want to create a specific N3PDF organization-user in  pypi or do I upload with my own user? The same for readthedocs and zenodo.

**Comment by scarrazza** [comment]
Yes, I think we should create an organization for N3PDF on all these sites (for Zenodo is not required, as the authors are listed explicitly and the name will contain the github/N3PDF prefix).

**Comment by scarlehoff** [comment]
Ok, I'll do so (name n3pdf in all cases) and use my own mail for now as we can change that later.

**Comment by scarrazza** [comment]
OK.

**Comment by scarlehoff** [comment]
So the pypi works and the conda-recipe for conda-forge seems to be working so everything is ready to go.
